### ISSUE TITLE
[BUG] @types/stream-mock outdated/inaccurate

### ISSUE THREAD

**Issue by RAnders00** [b4nst/stream-mock#29]
**Description**

These are the type definitions from `@types/stream-mock`:

```typescript
// Type definitions for stream-mock 1.2
// Project: https://github.com/BastienAr/stream-mock
// Definitions by: Ivan Kerin <https://github.com/ivank>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

/// <reference types="node" />

import {
    Readable,
    ReadableOptions,
    WritableOptions,
    Writable,
    Duplex,
    DuplexOptions
} from "stream";

export class ReadableMock extends Readable {
    constructor(source: ReadonlyArray<any>, opts?: ReadableOptions);
}
export class WritableMock extends Writable {
    data: any;
    flatData: any;
}
export class DuplexMock extends Duplex {
    data: any;
    flatData: any;
}
```

Which misses a lot of detail about type types and fields available **and** is inaccurate (for example the constructor signature shows as `constructor(opts?: DuplexOptions)` for `DuplexMock`, which is not the case because the source actually comes first, then the options.

I suggest replacing `@types/stream-mock` with a stub package, see https://github.com/DefinitelyTyped/DefinitelyTyped#removing-a-package

I'm not sure what version of `stream-mock` introduced type definitions in the npm package, I think 2.0? This commit seems to be relevant: https://github.com/b4nst/stream-mock/commit/5cce99d489e1dc538b14882ef1d37899f70dc892

**Comment by b4nst** [comment]
Hey @RAnders00, `@types/stream-mock` was created before I refactor this library as native Typescript. Now that it is Typescript, you don't need to install `@types/stream-mock`, `stream-mock` comes with its own type definition.

**Comment by b4nst** [comment]
Yep, version was 2.0.1 (2.0.0 was not released due to some bugs)

Pr incoming: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36565
